<a href="https://colab.research.google.com/github/u1353279/Feature-Selection/blob/master/StratifiedKfold_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import StratifiedKFold

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
df=pd.read_csv('/content/drive/My Drive/santandar.csv/train.csv')

In [3]:
df.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000       0
1   3     2     34  ...                     0.0   49278.030000       0
2   4     2     23  ...                     0.0   67333.770000       0
3   8     2     37  ...                     0.0   64007.970000       0
4  10     2     39  ...                     0.0  117310.979016       0

[5 rows x 371 columns]

In [4]:
#training and testing data
X=df.drop(columns=['ID','TARGET'],axis=1)
#test=df.drop(columns=['ID_code'],axis=1)
y=df['TARGET']

In [6]:
def get_correlation(data,threshold):
  corr_col=set()
  corrmat=data.corr()
  for i in range(len(corrmat.columns)):
    for j in range(i):
      if abs(corrmat.iloc[i,j])>threshold:
        colname=corrmat.columns[i]
        corr_col.add(colname)
  return corr_col

In [9]:
corr_features=get_correlation(X,0.85)

In [10]:
X_new=X.drop(labels=corr_features,axis=1)

In [12]:
X_new.shape

(76020, 177)

In [15]:
rf=RandomForestClassifier(n_estimators=100)
from sklearn.metrics import accuracy_score

In [16]:
accuracy=[]

skf=StratifiedKFold(n_splits=10,random_state=786)
skf.get_n_splits(X_new,y)

for train_index,test_index in skf.split(X_new,y):
  X1_train,X1_test=X_new.iloc[train_index],X_new.iloc[test_index]
  y1_train,y1_test=y.iloc[train_index],y.iloc[test_index]

  rf.fit(X1_train,y1_train)
  ypred=rf.predict(X1_test)
  score=accuracy_score(ypred,y1_test)
  accuracy.append(score)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning

In [17]:
print(accuracy)

[0.9547487503288609, 0.9496185214417259, 0.9544856616679821, 0.9525124967113917, 0.9535648513549067, 0.9522494080505131, 0.9515916863983163, 0.9544856616679821, 0.9539594843462247, 0.9533017626940279]